apiVersion: apps/v1
kind: Deployment
metadata:
  name: suricata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suricata
  template:
    metadata:
      labels:
        app: suricata
    spec:
      hostNetwork: true
      containers:
      - name: suricata
        image: suricata:latest
        imagePullPolicy: Never
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW", "SYS_NICE"]
        volumeMounts:
        - name: logs
          mountPath: /var/log/suricata
        - name: config
          mountPath: /etc/suricata/suricata.yaml
          subPath: suricata.yaml
        - name: rules
          mountPath: /var/lib/suricata/rules/custom.rules
          subPath: custom.rules
      volumes:
      - name: logs
        hostPath:
          path: /home/turki/Projet_fwk/suricata-logs
          type: DirectoryOrCreate
      - name: config
        configMap:
          name: suricata-config
      - name: rules
        configMap:
          name: suricata-rules
